### ISSUE TITLE
Migrate from Custom Component (Pre-Release) to OpenZWave (Beta)

### ISSUE THREAD

**Issue by i-am-snappy** [cgarwood/homeassistant-zwave_mqtt#138] opened 2020-06-07 12:01 UTC
Is there a migration path from the pre-release custom component to the official addon that I am missing? Or do we need to start from scratch with device and entity names etc.

I've tried a couple of times and lose all device and entity configurations and need to walk around house to find nodes and rename devices and entities.

**Comment by uSpike** [comment] 2020-06-07 13:58
AFAIK there is nothing yet to automatically migrate.  I think this is a duplicate of #19

**Comment by MartinHjelmare** [comment] 2020-06-07 21:06
Duplicate of #19

**Comment by i-am-snappy** [comment] 2020-06-08 11:31
Sorry, rephrasing my question as #19 seems to be centered around creating a migration path for the current Core zwave component. I have been testing the now deprecated Pre-Release Open-ZWave custom component.

Is there anything I can do - even manually - to pull Device and Entity data from the depricated daemon to the new OpenZWave integration?

Or, is it suggested to start from scratch again?

**Comment by MartinHjelmare** [comment] 2020-06-08 12:31
Sorry, I misunderstood the question.

The integration bases its data on the data that comes from the ozwdaemon via the mqtt broker. So if the daemon data and mqtt broker is the same, there should be no migration needed.

If you want to use the official ozwdaemon add-on instead of the custom add-on you would probably need to copy the ozwdaemon persistent data from the custom ozwdaemon add-on storage to the official add-on storage. I don't know the specifics there.

@marcelveldt do you have a better view of this?

**Comment by uSpike** [comment] 2020-06-08 13:27
Maybe I can help out since I've been dealing with this as well.

I don't think the official addon is ready yet due to https://github.com/home-assistant/hassio-addons/issues/1361.  This was fixed in https://github.com/OpenZWave/qt-openzwave/issues/75 but the hassio-addon has not been updated yet.  The version of qt-openzwave needs to be updated here https://github.com/home-assistant/hassio-addons/blob/master/zwave/build.json

Once that's done, you can "stop" your current 3rd party addon and copy `/usr/share/hassio/addons/data/62c7908d_ozwdaemon/ozwcache_0xXXXXXXXX.xml` (or wherever your hassio path is) to a safe location.  Then, install the new addon and copy the cache file into the similar location.  Should work fine.

**Comment by i-am-snappy** [comment] 2020-06-08 15:18
Thanks uSpike, Martin, I’ll wait for the persistent fix of the official OpenZWave addon to be rectified. Then will test out the XML move and report how I go. If I get a chance before the weekend, I’ll test regardless.

**Comment by i-am-snappy** [comment] 2020-06-14 14:21
Im running Home Assistant (the new Hass.io), is there a way to get to the addon data locations mentioned above? I've hunted around through the directories and cannot fing the ozwcache xml's.

**Comment by marcelveldt** [comment] 2020-07-06 14:26
There's no need to copy data. The mentioned xml file is a cache file only. If you wait a few days (or manually wake up all battery devices) all data will be gathered automatically again. Only if you have access to the filesystem of the supervisor you will be able to transfer the cache file if you really want to but again, it is not really needed.

**Closed as completed by marcelveldt** 2020-07-06 14:26 UTC
